import requests

def get_prices(product = 'google'):
    product = 'google'

    headers = {
        'Accept': 'application/json',
    }

    params = (
        ('product', product),
    )
    response = requests.get('https://5sim.net/v1/guest/prices', headers=headers, params=params)
    items = response.json()[product]
    for i in items:
        fastitem = next(iter(items[i].values()))
        fastitem['country']=i
        print(fastitem)
        print('.............................')
get_prices('google')
exit()


def codes(contry_name='United State'):
    data =[
    {"contry_code":+93,"contry_name":"Afghanistan"}, 
    {"contry_code":+355,"contry_name":"Albania"},
    {"contry_code":+213,"contry_name":"Algeria"}, 
    {"contry_code":+376,"contry_name":"Andorra"},
    {"contry_code":+244,"contry_name":"Angola"},
    {"contry_code":+54,"contry_name":"Argentina"},
    {"contry_code":+374,"contry_name":"Armenia"},
    {"contry_code":+297,"contry_name":"Aruba"},
    {"contry_code":+247,"contry_name":"Ascension"}, 
    {"contry_code":+61,"contry_name":"Australia"}, 
    {"contry_code":+672,"contry_name":"Australian External Territories"},
    {"contry_code":+43,"contry_name":"Austria"},
    {"contry_code":+994,"contry_name":"Azerbaijan"},
    {"contry_code":+973,"contry_name":"Bahrain"},
    {"contry_code":+880,"contry_name":"Bangladesh"}, 
    {"contry_code":+375,"contry_name":"Belarus"},
    {"contry_code":+32,"contry_name":"Belgium"},
    {"contry_code":+501,"contry_name":"Belize"}, 
    {"contry_code":+229,"contry_name":"Benin"}, 
    {"contry_code":+975,"contry_name":"Bhutan"},
    {"contry_code":+591,"contry_name":"Bolivia"},
    {"contry_code":+387,"contry_name":"Bosnia and Herzegovina"},
    {"contry_code":+267,"contry_name":"Botswana"},
    {"contry_code":+55,"contry_name":"Brazil"},
    {"contry_code":+673,"contry_name":"Brunei Darussalam"},
    {"contry_code":+359,"contry_name":"Bulgaria"},
    {"contry_code":+226,"contry_name":"Burkina Faso"},
    {"contry_code":+257,"contry_name":"Burundi"},
    {"contry_code":+855,"contry_name":"Cambodia"},
    {"contry_code":+237,"contry_name":"Cameroon"},
    {"contry_code":+238,"contry_name":"Cape Verde"},
    {"contry_code":+236,"contry_name":"Central African Republic"},
    {"contry_code":+235,"contry_name":"Chad"},
    {"contry_code":+56,"contry_name":"Chile"}, 
    {"contry_code":+57,"contry_name":"Colombia"}, 
    {"contry_code":+269,"contry_name":"Comoros"}, 
    {"contry_code":+242,"contry_name":"Congo"},
    {"contry_code":+682,"contry_name":"Cook Islands"},
    {"contry_code":+506,"contry_name":"Costa Rica"},
    {"contry_code":+225,"contry_name":"Cote dÕIvoire"}, 
    {"contry_code":+385,"contry_name":"Croatia"},
    {"contry_code":+53,"contry_name":"Cuba"},
    {"contry_code":+357,"contry_name":"Cyprus"},
    {"contry_code":+420,"contry_name":"Czech Republic"},
    {"contry_code":+243,"contry_name":"Democratic Republic of the Congo"},
    {"contry_code":+45,"contry_name":"Denmark"},
    {"contry_code":+246,"contry_name":"Diego Garcia"},
    {"contry_code":+253,"contry_name":"Djibouti"},
    {"contry_code":+670,"contry_name":"East Timor"},
    {"contry_code":+593,"contry_name":"Ecuador"},
    {"contry_code":+20,"contry_name":"Egypt"},
    {"contry_code":+503,"contry_name":"El Salvador"},
    {"contry_code":+240,"contry_name":"Equatorial Guinea"},
    {"contry_code":+291,"contry_name":"Eritrea"},
    {"contry_code":+372,"contry_name":"Estonia"},
    {"contry_code":+251,"contry_name":"Ethiopia"},
    {"contry_code":+500,"contry_name":"Falkland Islands"},
    {"contry_code":+298,"contry_name":"Faroe Islands"},
    {"contry_code":+679,"contry_name":"Fiji"},
    {"contry_code":+358,"contry_name":"Finland"},
    {"contry_code":+33,"contry_name":"France"},
    {"contry_code":+594,"contry_name":"French Guiana"},
    {"contry_code":+689,"contry_name":"French Polynesia"},
    {"contry_code":+241,"contry_name":"Gabon"},
    {"contry_code":+995,"contry_name":"Georgia"},
    {"contry_code":+49,"contry_name":"Germany"},
    {"contry_code":+233,"contry_name":"Ghana"}, 
    {"contry_code":+350,"contry_name":"Gibraltar"},
    {"contry_code":+30,"contry_name":"Greece"},
    {"contry_code":+299,"contry_name":"Greenland"},
    {"contry_code":+590,"contry_name":"Guadeloupe"},
    {"contry_code":+50,"contry_name":"Guinea"},
    {"contry_code":+592,"contry_name":"Guyana"},
    {"contry_code":+509,"contry_name":"Haiti"},
    {"contry_code":+504,"contry_name":"Honduras"},
    {"contry_code":+852,"contry_name":"Hong Kong"},
    {"contry_code":+36,"contry_name":"Hungary"},
    {"contry_code":+354,"contry_name":"Iceland"},
    {"contry_code":+91,"contry_name":"India"},
    {"contry_code":+62,"contry_name":"Indonesia"},
    {"contry_code":+98,"contry_name":"Iran"},
    {"contry_code":+964,"contry_name":"Iraq"},
    {"contry_code":+353,"contry_name":"Ireland"},
    {"contry_code":+972,"contry_name":"Israel"},
    {"contry_code":+39,"contry_name":"Italy"},
    {"contry_code":+81,"contry_name":"Japan"},
    {"contry_code":+962,"contry_name":"Jordan"},
    {"contry_code":+254,"contry_name":"Kenya"},
    {"contry_code":+686,"contry_name":"Kiribati"},
    {"contry_code":+965,"contry_name":"Kuwait"},
    {"contry_code":+996,"contry_name":"Kyrgyzstan"},
    {"contry_code":+856,"contry_name":"Laos"},
    {"contry_code":+371,"contry_name":"Latvia"},
    {"contry_code":+961,"contry_name":"Lebanon"},
    {"contry_code":+266,"contry_name":"Lesotho"},
    {"contry_code":+231,"contry_name":"Liberia"},
    {"contry_code":+218,"contry_name":"Libya"},
    {"contry_code":+423,"contry_name":"Liechtenstein"},
    {"contry_code":+370,"contry_name":"Lithuania"},
    {"contry_code":+352,"contry_name":"Luxembourg"},
    {"contry_code":+853,"contry_name":"Macao"},
    {"contry_code":+389,"contry_name":"Macedonia"},
    {"contry_code":+261,"contry_name":"Madagascar"},
    {"contry_code":+265,"contry_name":"Malawi"},
    {"contry_code":+60,"contry_name":"Malaysia"},
    {"contry_code":+960,"contry_name":"Maldives"},
    {"contry_code":+223,"contry_name":"Mali"},
    {"contry_code":+356,"contry_name":"Malta"},
    {"contry_code":+692,"contry_name":"Marshall Islands"},
    {"contry_code":+596,"contry_name":"Martinique"},
    {"contry_code":+222,"contry_name":"Mauritania"},
    {"contry_code":+230,"contry_name":"Mauritius"},
    {"contry_code":+52,"contry_name":"Mexico"},
    {"contry_code":+691,"contry_name":"Micronesia"},
    {"contry_code":+373,"contry_name":"Moldova"},
    {"contry_code":+377,"contry_name":"Monaco"},
    {"contry_code":+976,"contry_name":"Mongolia"},
    {"contry_code":+382,"contry_name":"Montenegro"},
    {"contry_code":+212,"contry_name":"Morocco"},
    {"contry_code":+258,"contry_name":"Mozambique"},
    {"contry_code":+95,"contry_name":"Myanmar"},
    {"contry_code":+264,"contry_name":"Namibia"},
    {"contry_code":+674,"contry_name":"Nauru"},
    {"contry_code":+977,"contry_name":"Nepal"},
    {"contry_code":+31,"contry_name":"Netherlands"},
    {"contry_code":+687,"contry_name":"New Caledonia"},
    {"contry_code":+64,"contry_name":"New Zealand"},
    {"contry_code":+505,"contry_name":"Nicaragua"},
    {"contry_code":+227,"contry_name":"Niger"},
    {"contry_code":+234,"contry_name":"Nigeria"},
    {"contry_code":+683,"contry_name":"Niue"},
    {"contry_code":+850,"contry_name":"North Korea"},
    {"contry_code":+47,"contry_name":"Norway"},
    {"contry_code":+968,"contry_name":"Oman"},
    {"contry_code":+92,"contry_name":"Pakistan"},
    {"contry_code":+680,"contry_name":"Palau"},
    {"contry_code":+970,"contry_name":"Palestine"},
    {"contry_code":+507,"contry_name":"Panama"},
    {"contry_code":+675,"contry_name":"Papua New Guinea"},
    {"contry_code":+595,"contry_name":"Paraguay"},
    {"contry_code":+51,"contry_name":"Peru"},
    {"contry_code":+63,"contry_name":"Philippines"},
    {"contry_code":+48,"contry_name":"Poland"},
    {"contry_code":+351,"contry_name":"Portugal"},
    {"contry_code":+974,"contry_name":"Qatar"},
    {"contry_code":+262,"contry_name":"Reunion"},
    {"contry_code":+40,"contry_name":"Romania"},
    {"contry_code":+7,"contry_name":"Russia"},
    {"contry_code":+250,"contry_name":"Rwanda"},
    {"contry_code":+290,"contry_name":"Saint Helena"},
    {"contry_code":+1,"contry_name":"Saint Kitts and Nevis"},
    {"contry_code":+1,"contry_name":"Saint Lucia"},
    {"contry_code":+508,"contry_name":"Saint Pierre and Miquelon"},
    {"contry_code":+1,"contry_name":"Saint Vincent and Grenadines"},
    {"contry_code":+685,"contry_name":"Samoa"},
    {"contry_code":+378,"contry_name":"San Marino"},
    {"contry_code":+239,"contry_name":"Sao Tome and Principe"},
    {"contry_code":+966,"contry_name":"Saudi Arabia"},
    {"contry_code":+221,"contry_name":"Senegal"},
    {"contry_code":+381,"contry_name":"Serbia"},
    {"contry_code":+248,"contry_name":"Seychelles"},
    {"contry_code":+232,"contry_name":"Sierra Leone"},
    {"contry_code":+65,"contry_name":"Singapore"},
    {"contry_code":+421,"contry_name":"Slovakia"},
    {"contry_code":+386,"contry_name":"Slovenia"},
    {"contry_code":+677,"contry_name":"Solomon Islands"},
    {"contry_code":+252,"contry_name":"Somalia"},
    {"contry_code":+27,"contry_name":"South Africa"},
    {"contry_code":+82,"contry_name":"South Korea"}, 
    {"contry_code":+34,"contry_name":"Spain"},
    {"contry_code":+94,"contry_name":"Sri Lanka"},
    {"contry_code":+249,"contry_name":"Sudan"},
    {"contry_code":+597,"contry_name":"Suriname"},
    {"contry_code":+268,"contry_name":"Swaziland"},
    {"contry_code":+46,"contry_name":"Sweden"},
    {"contry_code":+41,"contry_name":"Switzerland"},
    {"contry_code":+963,"contry_name":"Syria"},
    {"contry_code":+886,"contry_name":"Taiwan"},
    {"contry_code":+992,"contry_name":"Tajikistan"},
    {"contry_code":+255,"contry_name":"Tanzania"},
    {"contry_code":+66,"contry_name":"Thailand"},
    {"contry_code":+228,"contry_name":"Togo"},
    {"contry_code":+690,"contry_name":"Tokelau"},
    {"contry_code":+676,"contry_name":"Tonga"},
    {"contry_code":+1,"contry_name":"Trinidad and Tobago"},
    {"contry_code":+216,"contry_name":"Tunisia"},
    {"contry_code":+90,"contry_name":"Turkey"},
    {"contry_code":+993,"contry_name":"Turkmenistan"},
    {"contry_code":+688,"contry_name":"Tuvalu"},
    {"contry_code":+256,"contry_name":"Uganda"},
    {"contry_code":+380,"contry_name":"Ukraine"},
    {"contry_code":+971,"contry_name":"United Arab Emirates"},
    {"contry_code":+1,"contry_name":"United State"},
    {"contry_code":+598,"contry_name":"Uruguay"},
    {"contry_code":+998,"contry_name":"Uzbekistan "},
    {"contry_code":+678,"contry_name":"Vanuatu"}, 
    {"contry_code":+379,"contry_name":"Vatican City "},
    {"contry_code":+58,"contry_name":"Venezuela "},
    {"contry_code":+84,"contry_name":"Vietnam "},
    {"contry_code":+681,"contry_name":"Wallis and Futuna"},
    {"contry_code":+967,"contry_name":"Yemen"},
    {"contry_code":+260,"contry_name":"Zambia"},
    {"contry_code":+263,"contry_name":"Zimbabwe"},
    ]

    s_code='+1'
    for i in data:
        if i['contry_name'].casefold().replace(' ','')==contry_name.casefold().replace(' ',''):
            all_code = i['contry_code']
            strs = '+'+str(all_code)
            s_code = strs
            print(s_code)
            break
    return s_code
