[program:continar-monitor]
process_name=%(program_name)s_%(process_num)02d

command=python3 /root/monitor.py
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/root/monitor.log
stopwaitsecs=3600
