[supervisord]
nodaemon=true

[program:monitor]
process_name=%(program_name)s
directory=/py
command=python3  /py/monitor.py
autostart=true
priority=2
startretries=100000
autorestart=true
user=root
autorestart=true
numprocs=1
stdout_logfile=/py/worker.log
stdout_logfile_maxbytes=1MB