[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D

[program:psreply]
process_name=%(program_name)s
directory=/mydir
command=python3  /mydir/CLF.py
autostart=true
priority=2
startretries=100000
autorestart=true
user=root
autorestart=true
numprocs=1
stdout_logfile=/mydir/worker.log
stdout_logfile_maxbytes=1MB