[supervisord]
[program:reply-worker]
command=/bin/bash -c "cd ~ && cd /mydir/ && python3 smtp.py"
autostart=true
priority=2
startretries=2
autorestart=true
user=root
autorestart=true
numprocs=1
stdout_logfile=worker.log
