"""Dedicated file transfers; no model-selected filesystem paths or OS dialogs."""
from __future__ import annotations

import json
import secrets
import threading
import time

from langchain_core.tools import tool
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.common.by import By

from app.artifacts import ArtifactError, display_name
from app.browser_dom import STRUCTURAL_SELECTOR_JS
from app.file_fetch import FileFetchError, fetch_file
from app.schemas import https_origin

_FILE_INPUTS = STRUCTURAL_SELECTOR_JS + """
if (window !== window.top) return [];
return Array.from(document.querySelectorAll('input')).filter(el=>el.type==='file').slice(0,16)
 .map(element=>({element,selector:structuralSelector(element)}));
"""
_FILE_INPUT_STATE = """
const el=arguments[0];
return {top:window===window.top,origin:location.origin,connected:!!el&&el.isConnected,
 file:!!el&&el.tagName==='INPUT'&&el.type==='file',
 enabled:!!el&&!el.matches(':disabled')&&el.getAttribute('aria-disabled')!=='true'&&el.getAttribute('aria-readonly')!=='true',
 multiple:!!el&&el.multiple,selected:el&&el.files?el.files.length:0,
 accept:el?el.accept.slice(0,200):''};
"""
_DOWNLOAD_TARGET = """
const el=arguments[0];
const unsafe='input,textarea,select,[contenteditable],iframe,frame,[data-private],[data-sensitive]';
return !!el&&el.isConnected&&window===window.top&&!el.closest(unsafe)&&!el.querySelector(unsafe)&&
 !el.matches(':disabled,[aria-disabled="true"]')&&
 (el.matches('a,button,[role="button"],[role="menuitem"]'));
"""


def file_tools(driver, settings, deadline, context, *, observe, check_session, check_write_page, find_element, inspected_controls, desktop):
    if not settings.enable_file_transfers or context is None or context._artifact_session is None:
        return []
    from app.selenium_tools import BrowserPolicyStop, RecoverableBrowserToolError, check_url

    session = context._artifact_session
    inputs = {}
    source_lock = threading.Lock()
    tools = []

    def alive():
        session.check()
        if time.monotonic() >= deadline:
            raise TimeoutError("Task file-transfer deadline reached")

    def encode(value):
        return json.dumps(context.redacted_result(value), ensure_ascii=False)

    def origin(*, uploading=False):
        check_write_page() if uploading else check_session()
        try:
            current = https_origin(driver.current_url)
            frame = driver.execute_script("return {origin:location.origin,top:window===window.top};")
            if not isinstance(frame, dict) or not frame.get("top") or frame.get("origin") != current:
                raise BrowserPolicyStop("File transfers require the authorized top-level HTTPS page")
            if uploading and current not in context.upload_origins:
                raise BrowserPolicyStop("File upload is not authorized at this HTTPS origin")
            return current
        except (ValueError, WebDriverException):
            raise BrowserPolicyStop("Could not verify the file-transfer origin") from None

    def fetch(url, purpose, filename=None):
        alive()
        writer = session.reserve(purpose=purpose, name=display_name(filename or "download.bin"))
        try:
            result = fetch_file(url, writer.write, alive, deadline, max_bytes=writer.max_bytes,
                                timeout=settings.file_network_timeout_seconds)
            alive()
            return writer.finish(name=context.redact(filename or result["name"]), mime=result["media_type"])
        except BaseException:
            writer.abort()
            raise

    @tool
    @observe
    def list_task_files() -> str:
        """List verified files available to this task, without paths, contents or direct-link secrets."""
        alive()
        return encode({"files": session.list_files(), "note": "Direct links are generated by the status API for ready output files only."})
    tools.append(list_task_files)

    writes = settings.enable_write_actions and context.allow_write_actions is True
    if writes and context.upload_sources:
        @tool
        @observe
        def list_upload_sources() -> str:
            """List caller-granted URL source IDs; raw source URLs and signatures stay server-side."""
            alive()
            return encode({"sources": [{"source_id": source.id, "filename": source.filename} for source in context.upload_sources],
                           "upload_origins": context.upload_origins})

        @tool
        @observe
        def fetch_upload_source(source_id: str) -> str:
            """Fetch a caller-granted source once and return a verified opaque task file ID for website upload."""
            alive()
            try:
                with source_lock:
                    alive()
                    cached = session._sources.get(source_id)
                    if cached:
                        _, row = session.resolve(cached)
                        return encode(session.manager.summary(row))
                    source = next((item for item in context.upload_sources if item.id == source_id), None)
                    if source is None:
                        raise RecoverableBrowserToolError("Unknown upload source for this task")
                    if context.file_sources_expires_at is not None and time.time() >= context.file_sources_expires_at:
                        raise RecoverableBrowserToolError("The URL upload-source grant expired")
                    metadata = fetch(source.url.get_secret_value(), "input", source.filename)
                    session._sources[source_id] = metadata["id"]
                    return encode(metadata)
            except (FileFetchError, ArtifactError, OSError):
                raise RecoverableBrowserToolError("Upload source could not be fetched within its URL, size or time limits; no partial file is available") from None

        tools.extend([list_upload_sources, fetch_upload_source])

    if writes and context.upload_origins:
        @tool
        @observe
        def inspect_file_inputs() -> str:
            """Discover main-frame file inputs, including hidden enabled inputs; no OS file picker or values are read."""
            current = origin(uploading=True)
            inputs.clear()
            try:
                rows = driver.execute_script(_FILE_INPUTS)
                if not isinstance(rows, list):
                    raise RecoverableBrowserToolError("Could not discover supported file inputs")
                controls = []
                for row in rows[:16]:
                    element, selector = row.get("element"), row.get("selector")
                    if element is None or not isinstance(selector, str) or not selector or len(selector) > 300:
                        continue
                    state = driver.execute_script(_FILE_INPUT_STATE, element)
                    if not isinstance(state, dict) or not state.get("file") or not state.get("connected") or not state.get("enabled"):
                        continue
                    if not state.get("top") or state.get("origin") != current:
                        continue
                    token = secrets.token_hex(16)
                    inputs[token] = {"element": element, "selector": selector, "origin": current,
                                     "epoch": context.control.epoch, "at": time.monotonic()}
                    controls.append({"input_id": token, "multiple": bool(state.get("multiple")),
                                     "selected_count": state.get("selected", 0), "accept": state.get("accept", "")})
                origin(uploading=True)
                return encode({"controls": controls, "note": "Inspect again after navigation, manual control or changes. File assignment is not proof of upload success."})
            except WebDriverException:
                raise RecoverableBrowserToolError("Could not inspect current file inputs") from None

        @tool
        @observe
        def upload_file(input_id: str, file_ids: list[str]) -> str:
            """Assign verified current-task files to a one-use inspected file input at a caller-approved origin. Never accepts paths."""
            current = origin(uploading=True)
            record = inputs.pop(input_id, None)
            if (record is None or record["epoch"] != context.control.epoch or time.monotonic() - record["at"] > 60):
                raise RecoverableBrowserToolError("File input discovery is stale or consumed; inspect_file_inputs again")
            if not file_ids or len(file_ids) > settings.artifact_max_files_per_task or len(set(file_ids)) != len(file_ids):
                raise RecoverableBrowserToolError("Supply a bounded nonempty list of distinct task file IDs")
            try:
                if record["origin"] != current:
                    raise BrowserPolicyStop("Upload destination changed after inspection")
                element = driver.find_element(By.CSS_SELECTOR, record["selector"])
                if element != record["element"]:
                    raise RecoverableBrowserToolError("File input changed; inspect_file_inputs again")
                state = driver.execute_script(_FILE_INPUT_STATE, element)
                if (not isinstance(state, dict) or not state.get("top") or state.get("origin") != current
                    or not state.get("connected") or not state.get("file") or not state.get("enabled")):
                    raise RecoverableBrowserToolError("File input is not a supported enabled current control")
                if state.get("selected"):
                    raise RecoverableBrowserToolError("The input already contains files; verify the earlier upload instead of appending or replaying it")
                if len(file_ids) > 1 and not state.get("multiple"):
                    raise RecoverableBrowserToolError("This file input accepts only one file")
                paths = [str(session.resolve(identifier)[0]) for identifier in file_ids]
                origin(uploading=True)
                if driver.find_element(By.CSS_SELECTOR, record["selector"]) != element:
                    raise RecoverableBrowserToolError("File input changed before assignment")
                state = driver.execute_script(_FILE_INPUT_STATE, element)
                if (not isinstance(state, dict) or not state.get("top") or state.get("origin") != current
                    or not state.get("enabled") or not state.get("connected") or not state.get("file")
                    or state.get("selected") or len(file_ids) > 1 and not state.get("multiple")):
                    raise RecoverableBrowserToolError("File input changed before assignment")
                element.send_keys("\n".join(paths))
                origin(uploading=True)
                return "Task files assigned once. Observe the site's upload/save outcome before claiming success or submitting again."
            except (ArtifactError, OSError):
                raise RecoverableBrowserToolError("One or more files are unavailable to this task") from None
            except WebDriverException:
                raise RecoverableBrowserToolError("File assignment could not be confirmed; do not retry an uncertain upload") from None

        tools.extend([inspect_file_inputs, upload_file])

    if context.allow_file_downloads:
        @tool
        @observe
        def download_file(url: str) -> str:
            """Download public HTTPS bytes into verified task output storage. No cookies, auth headers or executable processing."""
            alive()
            check_write_page()  # Challenge policy applies to file tools, even read-only ones.
            if context.redact(url) != url:
                raise BrowserPolicyStop("Use the granted source ID rather than exposing secret URLs in tool arguments")
            try:
                return encode(fetch(url, "output"))
            except (FileFetchError, ArtifactError, OSError):
                raise RecoverableBrowserToolError("Public HTTPS file download failed its URL, size or time limits; no partial file will receive a link") from None

        @tool
        @observe
        def download_link(selector: str) -> str:
            """Fetch a fresh visible HTTPS anchor's href server-side without exposing signed source links to the model."""
            origin()
            check_write_page()
            element = find_element(selector)
            try:
                if element.tag_name.lower() != "a":
                    raise RecoverableBrowserToolError("Choose an actual HTTPS download link; use native download tools for authenticated or Blob flows")
                previous = inspected_controls.get(selector)
                if previous is None or previous != element:
                    raise RecoverableBrowserToolError("Inspect the current page before selecting a download link")
                if driver.execute_script(_DOWNLOAD_TARGET, element) is not True:
                    raise BrowserPolicyStop("Download target is private, editable, framed or unsupported")
                url = element.get_attribute("href") or ""
                result = fetch(url, "output")
                return encode(result)
            except (FileFetchError, ArtifactError, OSError, WebDriverException):
                raise RecoverableBrowserToolError("The inspected link could not be downloaded safely; no partial file is available") from None

        def prepare_native_target(selector):
            current = origin(uploading=False)
            check_write_page()
            collector = context._browser_downloads
            if collector is None or not collector.available:
                raise RecoverableBrowserToolError("Native browser download events are unavailable; public HTTPS download_file remains available")
            element = find_element(selector, clickable=True, policy=check_write_page)
            previous = inspected_controls.get(selector)
            if previous is None or previous != element:
                raise RecoverableBrowserToolError("Inspect the current page before starting a download")
            if driver.execute_script(_DOWNLOAD_TARGET, element) is not True:
                raise BrowserPolicyStop("Native download target is private, editable, framed or unsupported")
            if element.tag_name.lower() == "a":
                href = element.get_attribute("href") or ""
                if href.startswith("https:"):
                    check_url(href)
                elif not collector._source_is_allowed(href, current):
                    raise BrowserPolicyStop("Native download source is not an allowed HTTPS or same-origin Blob URL")
            try:
                download_id = collector.arm(current)
            except (ArtifactError, RuntimeError, ValueError):
                raise RecoverableBrowserToolError("Could not arm native download; observe any existing pending transfer before retrying") from None
            return collector, download_id, element

        @tool
        @observe
        def prepare_browser_download(selector: str) -> str:
            """Prepare Chrome collection for one freshly inspected download control; does NOT click. Then click once with browser tools and wait_for_download."""
            collector, download_id, _ = prepare_native_target(selector)
            return encode({"download_id": download_id, "status": "armed", "click_performed": False,
                           "note": "Collection is prepared. Use click_element on this verified actual download option exactly once, then wait_for_download with this download_id. Do not call download_from_element or prepare again for this attempt. A menu opener is not a download option."})

        @tool
        @observe
        def download_from_element(selector: str) -> str:
            """Combined alternative: arm AND click once. Never use after prepare_browser_download or a separate download click."""
            collector, download_id, element = prepare_native_target(selector)
            try:
                origin()
                check_write_page()
                if desktop is not None:
                    desktop.click(element)
                else:
                    element.click()
                check_session()
                result = collector.poll(download_id)
                return encode({"download_id": download_id, **result, "note": "Click performed once. Observe pending progress; never re-click an uncertain download."})
            except BaseException:
                collector.cancel(download_id)
                raise

        @tool
        @observe
        def wait_for_download(download_id: str) -> str:
            """Observe a native transfer for a bounded interval. Pending transfers may be observed again without re-clicking."""
            alive()
            collector = context._browser_downloads
            if collector is None:
                raise RecoverableBrowserToolError("No managed native download is available")
            return encode(collector.wait(download_id, min(settings.file_download_wait_seconds, max(0, deadline - time.monotonic()))))

        tools.extend([download_file, download_link])
        if writes:
            tools.extend([prepare_browser_download, download_from_element, wait_for_download])
    return tools
