[program:reply-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/python3.8 /root/reply/smtp.py
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/root/reply/reply.log
